config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :users, only: [:show]
  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  default_scope -> {order(dead: :asc)}
  validates :content, presence: true
  validates :dead, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable#, :confirmable
  validates :name, presence: true
  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end
#テスト

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    if user_signed_in?
      @event = Event.new
      @events = current_user.events.where("dead >= ?", Date.today)
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:success] = "イベントが作成されました"
      redirect_to root_url
    else
      flash.now[:danger] = "イベントが作成されませんでした"
      render 'new'
    end
  end

  def edit
  end

  def update
    if @event.update_attributes(event_params)
      flash[:success] = "イベントの編集が完了しました"
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event.destroy
    flash[:success] = "イベントを削除しました"
    redirect_to root_url
  end

  private
    def event_params
      params.require(:event).permit(:content, :dead, :user_id)
    end

    def correct_user
      @event = Event.find(params[:id])
      @user = User.find(@event.user_id)
      redirect_to(root_url) unless @user == current_user
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    sign_out if signed_in?
    redirect_to root_url
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find_by(id: params[:id])
    @events = @user.events.paginate(page: params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def event_dead_changer(event)
    today = Date.today
    if event.dead == today
      text = "今日です"
    elsif event.dead >= today
      #一度整数型に変換した後、文字列型に変換(分数で表示されるのを防ぐ)
      text = "あと：" + (event.dead - today).to_i.to_s + "日"
    else
      text = "経過：" + (today - event.dead).to_i.to_s + "日"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<% today = Date.today %>
<li>
  <a href="<%= event_path(event) %>">
  イベント名: <%= event.content %><br>
  期日： <%= event.dead %><br>
  <%= event_dead_changer(event) %>
  </a>
</li>

app/views/events/_form.html.erb
<%= form_for(@event, url: yield(:url)) do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>

  <%= f.label :content %>
  <%= f.text_field :content %><br>

  <%= f.label :dead %>
  <%= f.date_field :dead, value: Date.tomorrow %>

  <%= f.submit yield(:button_text) %>
<% end %>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<% provide(:url, event_path) %>
<% provide(:button_text, "変更") %>

<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

<%= render 'form' %>

app/views/events/index.html.erb
<% provide(:url, events_path) %>
<% provide(:button_text, "追加") %>

<h1><%= current_user.name %></h1>
<p>Find me in app/views/events/index.html.erb</p>

<% if signed_in? %>
<ul>
  <%= render @events %>
</ul>

<aside>
  <%= render 'form' %>
</aside>
<% else %>
<p>ログインしてください</p>
<%= link_to "ログイン", new_user_session_path %>
<% end %>

app/views/events/new.html.erb
<% provide(:url, events_path) %>
<% provide(:button_text, "追加") %>

<h1>Events#new</h1>

<%= render 'form' %>

app/views/events/show.html.erb
<h1>Events#show</h1>
<p>Find me in app/views/events/show.html.erb</p>

<% unless @event.nil? %>
  <p>イベント名:
  <%= @event.content %></p>

  <p>期日:
  <%= @event.dead %></p>

  <p><%= event_dead_changer(@event) %></p>
  <%= link_to "編集", edit_event_path(@event) %>
  <%= link_to "削除", event_path(@event), method: :delete %>
<% else %>
  <p>イベントが存在しません</p>
<% end -%>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/layouts/_header.html.erb
<header class="navbar">
  <div class="container">
    <%= link_to "逆算カレンダー", root_path, id: "logo" %>
    <nav>
      <ul class="nav">
        <li><%= link_to "イベント追加", new_event_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "プロフィール", current_user %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gyakusan</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to t(".sign_in"), new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to t(".sign_up"), new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to t(".forgot_your_password"), new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to t('.didn_t_receive_confirmation_instructions'), new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to t('.didn_t_receive_unlock_instructions'), new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to t('.sign_in_with_provider', provider: provider.to_s.titleize), omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<p>名前:<%= @user.name %></p>
<%= link_to "編集", edit_user_registration_path(@user) %>

<p>イベントリスト</p>
<p>イベント数：<%= @events.count %></p>
<% if @user.events.any? %>
<ol>
  <%= render @events %>
</ol>
<%= will_paginate @events %>
<% end %>